const nodemailer = require('nodemailer');
const fs = require('fs');
const path = require('path');
require('dotenv').config();

// Create transporter if SMTP configs exist, otherwise mock
let transporter = null;
if (process.env.SMTP_HOST && process.env.SMTP_USER) {
  transporter = nodemailer.createTransport({
    host: process.env.SMTP_HOST,
    port: parseInt(process.env.SMTP_PORT || '587'),
    secure: process.env.SMTP_SECURE === 'true' || process.env.SMTP_PORT === '465',
    auth: {
      user: process.env.SMTP_USER,
      pass: process.env.SMTP_PASS
    }
  });
}

/**
 * Sends a job requirements email to a vendor.
 * Generates an HTML layout and either delivers it via SMTP or writes it locally as HTML.
 */
async function sendJobOutreach(vendor, job, requiredSkills, preferredSkills) {
  const uploadUrl = `http://localhost:5173/vendor-submit?jobId=${job.id}&vendorId=${vendor.id}`;
  
  const htmlContent = `
    <!DOCTYPE html>
    <html>
    <head>
      <style>
        body { font-family: Arial, sans-serif; line-height: 1.6; color: #333; }
        .container { max-width: 600px; margin: 0 auto; padding: 20px; border: 1px solid #ddd; border-radius: 8px; }
        .header { background-color: #0f172a; color: #fff; padding: 15px; text-align: center; border-radius: 6px 6px 0 0; }
        .content { padding: 20px; }
        .button { display: inline-block; padding: 10px 20px; background-color: #2563eb; color: #ffffff !important; text-decoration: none; border-radius: 5px; font-weight: bold; margin-top: 15px; }
        .footer { font-size: 12px; color: #777; margin-top: 20px; text-align: center; border-top: 1px solid #eee; padding-top: 10px; }
        .details-table { width: 100%; border-collapse: collapse; margin-top: 15px; }
        .details-table td { padding: 8px; border-bottom: 1px solid #eee; }
        .details-table td:first-child { font-weight: bold; width: 35%; color: #555; }
      </style>
    </head>
    <body>
      <div class="container">
        <div class="header">
          <h2>Candidate Request - Staffing Augmentation</h2>
        </div>
        <div class="content">
          <p>Hello <strong>${vendor.name}</strong> Team,</p>
          <p>We are currently looking for qualified candidates for the following position. Based on your specialties, we would appreciate it if you could submit matching profiles from your network.</p>
          
          <table class="details-table">
            <tr>
              <td>Job Title</td>
              <td>${job.title}</td>
            </tr>
            <tr>
              <td>Required Skills</td>
              <td>${requiredSkills.join(', ') || 'None specified'}</td>
            </tr>
            <tr>
              <td>Preferred Skills</td>
              <td>${preferredSkills.join(', ') || 'None specified'}</td>
            </tr>
            <tr>
              <td>Required Experience</td>
              <td>${job.experience_years ? `${job.experience_years} years` : 'Open'}</td>
            </tr>
            <tr>
              <td>Client Budget</td>
              <td>${job.budget ? `$${job.budget} max` : 'Not disclosed'}</td>
            </tr>
          </table>

          <p style="margin-top: 20px;"><strong>Submission Instructions:</strong><br/>
          Please click the link below to submit candidate resumes directly to our parsing system. Candidates will be automatically scored against our JD.</p>

          <p style="text-align: center;">
            <a href="${uploadUrl}" class="button" target="_blank">Attach Candidate Resumes</a>
          </p>
          
          <p style="font-size: 11px; color: #888; text-align: center; margin-top: 10px;">
            Or copy this URL: <br/>${uploadUrl}
          </p>

          <p>Thank you,<br/><strong>Alphaxine Recruitment Team</strong></p>
        </div>
        <div class="footer">
          This is an automated request generated by the Alphaxine Staffing System.
        </div>
      </div>
    </body>
    </html>
  `;

  const mailOptions = {
    from: process.env.SMTP_FROM || '"Alphaxine System" <recruitment@alphaxine.com>',
    to: vendor.email,
    subject: `[OUTSOURCE REQUEST] Resumes requested for: ${job.title}`,
    html: htmlContent
  };

  if (transporter) {
    try {
      const info = await transporter.sendMail(mailOptions);
      console.log(`Email successfully sent to ${vendor.email}: ${info.messageId}`);
      return { success: true, mode: 'SMTP', messageId: info.messageId };
    } catch (error) {
      console.error(`Error sending email to ${vendor.email} via SMTP:`, error.message);
      // Fall back to local file logging on SMTP failure
    }
  }

  // Local Mock Logging
  try {
    const sentEmailsDir = path.join(__dirname, '../sent_emails');
    if (!fs.existsSync(sentEmailsDir)) {
      fs.mkdirSync(sentEmailsDir, { recursive: true });
    }
    const safeSubject = `outreach_${job.id}_${vendor.id}_${Date.now()}.html`;
    const filePath = path.join(sentEmailsDir, safeSubject);
    fs.writeFileSync(filePath, htmlContent, 'utf-8');
    console.log(`Mock email written locally: ${filePath}`);
    return { success: true, mode: 'LOCAL_MOCK', path: `sent_emails/${safeSubject}` };
  } catch (error) {
    console.error('Error writing mock email locally:', error.message);
    throw error;
  }
}

/**
 * Sends a client proposal email.
 * Evaluates SMTP first, and keeps a local mock log.
 */
async function sendClientProposal(clientEmail, subject, htmlContent, jobId, attachments = []) {
  const mailOptions = {
    from: process.env.SMTP_FROM || '"Alphaxine System" <recruitment@alphaxine.com>',
    to: clientEmail,
    subject: subject,
    html: htmlContent,
    attachments: attachments
  };

  if (transporter) {
    try {
      const info = await transporter.sendMail(mailOptions);
      console.log(`Email successfully sent to ${clientEmail}: ${info.messageId}`);
    } catch (error) {
      console.error(`Error sending email to ${clientEmail} via SMTP:`, error.message);
    }
  }

  // Always keep a local log as requested by the user
  try {
    const sentEmailsDir = path.join(__dirname, '../sent_emails');
    if (!fs.existsSync(sentEmailsDir)) {
      fs.mkdirSync(sentEmailsDir, { recursive: true });
    }
    const fileName = `client_proposal_${jobId}_batch_${Date.now()}.html`;
    const filePath = path.join(sentEmailsDir, fileName);
    fs.writeFileSync(filePath, htmlContent, 'utf-8');
    console.log(`Client proposal mock written locally: ${filePath}`);
    return { success: true, filePath };
  } catch (error) {
    console.error('Error writing client proposal locally:', error.message);
    throw error;
  }
}

async function sendVerificationEmail(email, token) {
  const backendUrl = process.env.BACKEND_URL || 'http://localhost:5000';
  const yesUrl = `${backendUrl}/api/auth/verify-email-link?token=${token}&action=yes`;
  const noUrl = `${backendUrl}/api/auth/verify-email-link?token=${token}&action=no`;
  
  const htmlContent = `
    <!DOCTYPE html>
    <html>
    <head>
      <style>
        body { font-family: Arial, sans-serif; line-height: 1.6; color: #333; }
        .container { max-width: 600px; margin: 0 auto; padding: 20px; border: 1px solid #ddd; border-radius: 8px; }
        .header { background-color: #0f172a; color: #fff; padding: 15px; text-align: center; border-radius: 6px 6px 0 0; }
        .content { padding: 20px; text-align: center; }
        .button { display: inline-block; padding: 10px 20px; color: #ffffff !important; text-decoration: none; border-radius: 5px; font-weight: bold; margin: 10px; }
        .btn-yes { background-color: #22c55e; }
        .btn-no { background-color: #ef4444; }
        .footer { font-size: 12px; color: #777; margin-top: 20px; text-align: center; border-top: 1px solid #eee; padding-top: 10px; }
      </style>
    </head>
    <body>
      <div class="container">
        <div class="header">
          <h2>Verify Your Email</h2>
        </div>
        <div class="content">
          <p>Hello,</p>
          <p>We received a request to use this email address (<strong>${email}</strong>) to create an account on Alphaxine.</p>
          <p>Was this you?</p>
          
          <div>
            <a href="${yesUrl}" class="button btn-yes" target="_blank">Yes, it's me</a>
            <a href="${noUrl}" class="button btn-no" target="_blank">No, it's not me</a>
          </div>
        </div>
        <div class="footer">
          If you did not request this, please click "No, it's not me" or ignore this email.
        </div>
      </div>
    </body>
    </html>
  `;

  const mailOptions = {
    from: process.env.SMTP_FROM || '"Alphaxine System" <recruitment@alphaxine.com>',
    to: email,
    subject: `Verify your email for Alphaxine`,
    html: htmlContent
  };

  if (transporter) {
    try {
      const info = await transporter.sendMail(mailOptions);
      console.log(`Verification email sent to ${email}: ${info.messageId}`);
    } catch (error) {
      console.error(`Error sending verification email to ${email} via SMTP:`, error.message);
    }
  }

  // Always keep a local log for debugging
  try {
    const sentEmailsDir = path.join(__dirname, '../sent_emails');
    if (!fs.existsSync(sentEmailsDir)) {
      fs.mkdirSync(sentEmailsDir, { recursive: true });
    }
    const fileName = `verification_${Date.now()}.html`;
    const filePath = path.join(sentEmailsDir, fileName);
    fs.writeFileSync(filePath, htmlContent, 'utf-8');
    console.log(`Verification email mock written locally: ${filePath}`);
    return { success: true, filePath };
  } catch (error) {
    console.error('Error writing verification email locally:', error.message);
    throw error;
  }
}

async function sendLoginOtpEmail(email, otp) {
  const htmlContent = `
    <!DOCTYPE html>
    <html>
    <head>
      <style>
        body { font-family: Arial, sans-serif; line-height: 1.6; color: #333; }
        .container { max-width: 600px; margin: 0 auto; padding: 20px; border: 1px solid #ddd; border-radius: 8px; }
        .header { background-color: #0f172a; color: #fff; padding: 15px; text-align: center; border-radius: 6px 6px 0 0; }
        .content { padding: 20px; text-align: center; }
        .otp-code { font-size: 32px; font-weight: bold; letter-spacing: 5px; color: #E84E20; margin: 20px 0; }
        .footer { font-size: 12px; color: #777; margin-top: 20px; text-align: center; border-top: 1px solid #eee; padding-top: 10px; }
      </style>
    </head>
    <body>
      <div class="container">
        <div class="header">
          <h2>Your Alphaxine Login Code</h2>
        </div>
        <div class="content">
          <p>Hello,</p>
          <p>Please use the following 6-digit code to complete your login:</p>
          <div class="otp-code">${otp}</div>
          <p>This code will expire in 5 minutes.</p>
        </div>
        <div class="footer">
          If you did not attempt to log in, please secure your account or ignore this email.
        </div>
      </div>
    </body>
    </html>
  `;

  const mailOptions = {
    from: process.env.SMTP_FROM || '"Alphaxine System" <recruitment@alphaxine.com>',
    to: email,
    subject: `Your Login Code: ${otp}`,
    html: htmlContent
  };

  if (transporter) {
    try {
      const info = await transporter.sendMail(mailOptions);
      console.log(`Login OTP email sent to ${email}: ${info.messageId}`);
    } catch (error) {
      console.error(`Error sending Login OTP email to ${email} via SMTP:`, error.message);
    }
  }

  // Always keep a local log for debugging
  try {
    const sentEmailsDir = path.join(__dirname, '../sent_emails');
    if (!fs.existsSync(sentEmailsDir)) {
      fs.mkdirSync(sentEmailsDir, { recursive: true });
    }
    const fileName = `login_otp_${Date.now()}.html`;
    const filePath = path.join(sentEmailsDir, fileName);
    fs.writeFileSync(filePath, htmlContent, 'utf-8');
    console.log(`Login OTP email mock written locally: ${filePath}`);
    return { success: true, filePath };
  } catch (error) {
    console.error('Error writing login OTP email locally:', error.message);
    throw error;
  }
}

module.exports = {
  sendJobOutreach,
  sendClientProposal,
  sendVerificationEmail,
  sendLoginOtpEmail
};
